[package]
name = "cargo-altvup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-altvup"

[dependencies]
colored = "2.0.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.163", features = ["derive"] }
